# action.yml
name: "Rust Cargo Deb Package Build (armv7, Debian)"
description: "Builds a debian package using cargo deb for Rust packages, statically linked (musl), targeting ARMv7"
branding:
  icon: "package"
  color: "orange"
inputs:
  cmd:
    description: "build command"
    required: true
    default: "cargo deb --target=armv7-unknown-linux-musleabihf"
runs:
  using: "docker"
  image: "docker://eghcr.io/wouterdebie/cargo-deb-armv7-debian:1.0"
  args:
    - ${{ inputs.cmd }}
